project_name: lnd
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/sysatom/lnd/internal/build.Version={{.Version}}
      - -X github.com/sysatom/lnd/internal/build.Commit={{.Commit}}
      - -X github.com/sysatom/lnd/internal/build.Date={{.Date}}
      - -X github.com/sysatom/lnd/internal/build.BuiltBy=goreleaser
    main: ./cmd/lnd
    binary: lnd
archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- .Arch }}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  extra_files:
    - glob: scripts/install.sh

